---
# Practicalli Clojure
site_name: Practicalli Clojure
site_url: https://practical.li/clojure
dev_addr: '0.0.0.0:8000'
site_description: Practical guide to Clojure programming language and Clojure REPL driven development
site_author: Practicalli
copyright: Copyright &copy 2023  Practicali <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>
repo_url: https://github.com/practicalli/clojure/
edit_uri: https://github.com/practicalli/clojure/edit/main/docs/

# Deployment
# remote_name: origin
remote_branch: gh-pages # deployment branch

# Theme and styling
theme:
  name: material
  logo: assets/images/practicalli-logo.png
  favicon: assets/favicon.svg
  features:
    - announce.dismiss
    - navigation.top
    - content.code.annotate
    - content.tabs.link
    - content.code.copy
    - content.action.edit
    - content.action.view
    - navigation.instant # Avoid page reloading for internal links
    - navigation.tracking # Update URL with anchor
    - navigation.indexes # Nav sections can have files
    - navigation.footer
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  # Override theme
  custom_dir: overrides

extra_css:
  - assets/stylesheets/extra.css

## Additional styling
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html # Grids
  - footnotes # footnotes and abbreviations
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys # keyboard keys
  - pymdownx.magiclink
  - def_list # lists
  - pymdownx.tasklist:
      custom_checkbox: true # checkboxes
  - toc:
      permalink: λ︎

## Plugins
plugins:
  - with-pdf
  # Explicitly add search plugin when defining plugins in this configuration file
  - search
  - callouts
  - glightbox # Image aligning
  - git-revision-date-localized: # Update and Creation date of each page
      # enable_creation_date: true
      fallback_to_build_date: true

  # Generate Social Cards via CI only
  # in assets/images/social
  - social:
      cards: !ENV [MKDOCS_SOCIAL_CARDS_GENERATE, true]

  # Redirect pages when moved or changed
  - redirects:
      redirect_maps:
        repl-driven-development.md: introduction/repl-workflow.md
        clojure-cli/data-browsers/index.md: data-inspector/index.md
        clojure-editors/editor-install-guides/vspacecode-calva.md: clojure-editors/index.md
        clojure-editors/editor-user-guides/vspacecode-calva.md: clojure-editors/index.md

# Footer / Social Media
extra:
  analytics:
    provider: google
    property: G-QZ22Z9DH4T
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jr0cket/
    - icon: fontawesome/brands/slack
      link: https://clojurians.slack.com/messages/practicalli
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/practical_li
    - icon: fontawesome/brands/github
      link: https://github.com/practicalli
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/practicalli

# Navigation
nav:
  - Introduction:
      - index.md
      - Clojure in Fifteen Mins: introduction/clojure-in-15-minutes.md
      - REPL Workflow: introduction/repl-workflow.md
      - Concepts:
          - introduction/concepts/index.md
          - Functional vs Imperative: introduction/concepts/what-is-functional-programming.md
          - From The Author: introduction/concepts/clojure-made-simple.md
          # - introduction/concepts/purpose.md
      # - introduction/learning-clojure.md
      # - introduction/who-uses-clojure.md
      - Contributing: introduction/contributing.md
      - Writing Tips: introduction/writing-tips.md
  - Install:
      - install/index.md
      - Java Host: install/java.md
      - Clojure CLI: install/clojure-cli.md
  - Clojure CLI Overview:
      - clojure-cli/index.md
      - Practicalli Config: clojure-cli/practicalli-config.md
      - Built-in Commands: clojure-cli/built-in-commands.md
      - Defining aliases: clojure-cli/defining-aliases.md
      - Execution Options: clojure-cli/execution-options.md
      - REPL Reloaded: clojure-cli/repl-reloaded.md
      - Clojure Style: clojure-cli/clojure-style.md
  - Terminal REPL:
      - clojure-cli/repl/index.md
      - REPL Coding: clojure-cli/repl/coding.md
      - REPL Libraries: clojure-cli/repl/libraries.md
      - REPL Help: clojure-cli/repl/help.md
      - REPL troubleshoot: clojure-cli/repl/troubleshooting.md
      # <!-- - clojure-cli/repl/repl-uncovered.md --> <!-- TODO rewrite -->
  - REPL Startup: clojure-cli/repl-startup.md
  - Clojure Projects:
      - clojure-cli/projects/index.md
      - From Template: clojure-cli/projects/create-from-template.md
      - Add Libraries: clojure-cli/projects/add-libraries.md
      - Namespaces: clojure-cli/projects/namespace.md
      - Rich Comment: clojure-cli/projects/rich-comments.md
      - Hotload in Project: clojure-cli/projects/hotload-in-project.md
      - Migrate projects: clojure-cli/projects/migrate-project.md
      - Package: clojure-cli/projects/tools-build.md
  - Clojure Editors:
      - clojure-editors/index.md
      - Clojure LSP:
          - clojure-editors/clojure-lsp/index.md
          - Clojure LSP Snippets: clojure-editors/clojure-lsp/snippets.md
          - Practicalli Snippets: clojure-editors/clojure-lsp/practicalli-snippets.md
  - Automation:
      - automation/index.md
      - Make: automation/make.md
      # - Shell Scripts: automation/shell-scripts.md
      # - Babashka: automation/babashka.md
  - Data Inspectors:
      - data-inspector/index.md
      - data-inspector/clojure-inspector.md
      - Portal: data-inspector/portal.md
  - Code Challenges:
      - coding-challenges/index.md
      - 4 Ever Clojure:
          - coding-challenges/4clojure/index.md
      - Exercism:
          - coding-challenges/exercism/index.md
          - coding-challenges/exercism/rna-transcription.md
          # - coding-challenges/exercism/hamming.md
          # - coding-challenges/exercism/space-age.md
          - Bob:
              - coding-challenges/exercism/bob/index.md
              - coding-challenges/exercism/bob/bob-string-approach.md
              - coding-challenges/exercism/bob/bob-regular-expression-approach.md
      - CodeWars: coding-challenges/codewars/index.md
      - Advent Of Code: coding-challenges/advent-of-code.md
      - Simple projects:
          - simple-projects/index.md
          - Random Function: simple-projects/random-clojure-function.md
          # - Salary Calculator: simple-projects/salary-calculator.md
          - Encoder Decode:
              - simple-projects/encode-decode/index.md
              - simple-projects/encode-decode/convert-boolean-values.md
              - simple-projects/encode-decode/caesar-cipher-rot13.md
              - simple-projects/encode-decode/rna-dna.md
              - simple-projects/encode-decode/clacks.md
          - Data Transform:
              - simple-projects/data-transformation/index.md
              - simple-projects/data-transformation/most-common-word.md
          - Kata:
              - simple-projects/tdd-kata/index.md
              - Recent Song list: simple-projects/tdd-kata/recent-song-list.md
      - Games:
          - games/index.md
          # Convert to deps.edn
          - TicTacToe:
              - games/tictactoe-cli/index.md
  - Testing:
      - testing/index.md
      - Unit Testing:
          - testing/unit-testing/index.md
          - Writing Tests: testing/unit-testing/writing-unit-tests.md
          - Fixtures: testing/unit-testing/fixtures.md
          - Test Selectors: testing/unit-testing/test-selectors.md
          # <!-- - [TDD Kata: Recent Song-ltesting/unit-testing/tdd-kata/recent-song-list.md -->
          # <!-- - testing/unit-testing/clojure-test-expectations.md -->
      - Test runners:
          - testing/test-runners/index.md
          - Kaocha: testing/test-runners/kaocha-test-runner.md
          - Cognitect Labs: testing/test-runners/congnitect-labs-test-runner.md
          - Example Projects: testing/test-runners/example-projects.md
  - Clojure Spec:
      - clojure-spec/index.md
      - REPL Experiments: clojure-spec/using-spec-in-the-repl.md
      - Project config: clojure-spec/add-spec-to-projects.md
      - Organise spec: clojure-spec/organising-specs.md
      - Data Specs:
          - clojure-spec/data/index.md
          - clojure-spec/data/predicate-specifications.md
          - clojure-spec/data/literal-values.md
          - clojure-spec/data/conform.md
          - clojure-spec/data/valid-q.md
          - clojure-spec/data/explain.md
          - clojure-spec/data/defining-specifications.md
          - clojure-spec/data/registry.md
          - clojure-spec/data/entity-maps.md
          - clojure-spec/data/map-literals.md
          - clojure-spec/data/and-or-specifications.md
          - clojure-spec/data/composite-specifications.md
          - clojure-spec/data/hierarchical-specifications.md
      - Function Specs:
          - clojure-spec/functions/index.md
          - clojure-spec/functions/function-definition-specifications.md
          - clojure-spec/functions/documentation.md
          - clojure-spec/functions/higher-order-functions.md
      - Testing:
          - clojure-spec/testing/index.md
          - clojure-spec/testing/checking arguments.md
          # <!-- - clojure-spec/defining-specifications/index.md -->
          - Generative Testing:
              - clojure-spec/generative-testing/index.md
              - clojure-spec/generative-testing/predicate-generators.md
              # <!-- - clojure-spec/generative-testing/generating-generators.md -->
              - clojure-spec/generative-testing/example-projects/index.md
              - clojure-spec/generative-testing/example-projects/next-jdbc.md
      - Spec Project:
          - clojure-spec/projects/index.md
          # <!-- Checking for bad names in ns declarations, lets, etc. -->
          # <!-- - clojure-spec/projects/convention-checks.md -->
          - Playing Cards:
              - clojure-spec/projects/card-game/index.md
          - Bank Account:
              - clojure-spec/projects/bank-account/index.md
              # <!-- - clojure-spec/projects/bank-account/create-project.md -->
              - clojure-spec/projects/bank-account/write-failing-tests.md
              - clojure-spec/projects/bank-account/customer-details-specification.md
              - clojure-spec/projects/bank-account/validate-customer-details-specification.md
              - clojure-spec/projects/bank-account/account-holder-specification.md
              - clojure-spec/projects/bank-account/generate-test-data.md
              - clojure-spec/projects/bank-account/unit-tests-with-spec.md
              - clojure-spec/projects/bank-account/function-specifications.md
              - clojure-spec/projects/bank-account/test-functions-against-spec.md

  - Continuous Integration:
      - continuous-integration/index.md
      - Circle CI:
          - continuous-integration/circle-ci/index.md
          - continuous-integration/circle-ci/random-clojure-function.md
          - continuous-integration/circle-ci/status-monitor.md
          # <!-- - continuous-integration/circle-ci/circle-ci-sample-project.md -->
      - GitHub Workflow:
          - continuous-integration/github-workflow/index.md
  # <!-- - testing/performance-testing/index.md -->
  # <!-- - testing/load-stress-testing/index.md -->

  - Reference:
      - reference/index.md
      - quickstart/quick-reference.md
      - Clojure CLI:
          - reference/clojure-cli/index.md
          # <!-- - [deps.edn aliases](clojure-cli/configure/deps-edn-aliases.md) -->
          - reference/clojure-cli/defining-aliases.md
          - reference/clojure-cli/example-alias-definitions.md
          - reference/clojure-cli/jvm-options.md
          # - clojure-cli/configure/common-tasks.md
          # - clojure-cli/configure/defining-aliases.md
      - Code Analysis: reference/code-analysis.md
      - Standard Library:
          - reference/standard-library/index.md
          - reference/standard-library/destructuring.md
          - reference/standard-library/predicate-functions.md
          - Regular Expressions:
              - reference/standard-library/regular-expressions/index.md
              - reference/standard-library/regular-expressions/matching-with-groups.md
              - reference/standard-library/regular-expressions/matching-sub-strings.md
              - reference/standard-library/regular-expressions/matching-sub-sequences.md
              - reference/standard-library/regular-expressions/common-regex-patterns.md
              - reference/standard-library/regular-expressions/string-replace-with-regex.md
              - reference/standard-library/regular-expressions/string-split-with-regex.md
              - reference/standard-library/regular-expressions/sub-expression-matches.md
          - reference/standard-library/cond-thread-macro.md
      - Java:
          - reference/clojure-syntax/java-interop.md
          - More Java fun: reference/clojure-syntax/more-java-fun.md

      # Move syntax into a reference section and use projects to expose audience to Clojure syntax
      # Basic syntax and calling functions
      - Clojure Syntax:
          - reference/clojure-syntax/syntax.md
          - reference/clojure-syntax/parenthesis.md
          - reference/clojure-syntax/code-documentation.md
          - reference/clojure-syntax/comments.md
          - reference/clojure-syntax/strings.md
          - reference/clojure-syntax/numbers-maths.md
          - reference/clojure-syntax/ratios.md
          - reference/clojure-syntax/control-flow.md
          - reference/doc-and-source-functions.md
          - reference/clojure-syntax/assigning-names.md
          - reference/clojure-syntax/naming.md
          - reference/kebab-case.md
          - reference/threading-macros.md
          - reference/tagged-literals/index.md
          - reference/tagged-literals/uuid.md
      # Persistent data structures list vector map set -->
      - Data Structures:
          - data-structures/index.md
          - data-structures/list.md
          - data-structures/hash-maps/index.md
          - data-structures/hash-maps/create.md
          - data-structures/hash-maps/access.md
          # - data-structures/hash-maps/update.md
          - data-structures/vector.md
          - data-structures/set.md
          - data-structures/naming.md
          - data-structures/shared-memory.md
          - Pretty Printing: data-structures/pretty-printing.md
          - Using Data Structures:
              - using-data-structures/index.md
              - using-data-structures/sequences.md
              - using-data-structures/lazy-sequences.md
              - using-data-structures/destructuring.md
              - using-data-structures/applying-functions.md
              - using-data-structures/mapping-data-structures.md
          - Modifying:
              - modifying-data-structures/index.md
              - modifying-data-structures/lists.md
              - modifying-data-structures/maps.md
              - modifying-data-structures/vectors.md
              - modifying-data-structures/sets.md
          - iterate-over-data/index.md
          - iterate-over-data/map.md
          - iterate-over-data/map-partial.md
          - iterate-over-data/map-fn.md
          - iterate-over-data/filter-remove.md
          - iterate-over-data/apply.md
          - iterate-over-data/reduce.md
          - iterate-over-data/reduce.md
          - iterate-over-data/reduce.md
          - Design:
              - designing-data-structures/index.md
              - designing-data-structures/with-vectors.md
              - designing-data-structures/with-vectors-of-vectors.md
              - designing-data-structures/with-maps.md
              - designing-data-structures/with-maps-of-maps.md
              - designing-data-structures/with-vectors-of-maps.md
              - designing-data-structures/modeling-alphabet-codes.md
              - designing-data-structures/modeling-name-generation-map.md
      - Thinking Functionally:
          - thinking-functionally/index.md
          - thinking-functionally/side-effects.md
          - thinking-functionally/pure-functions.md
          - thinking-functionally/impure-functions.md
          - thinking-functionally/first-class-functions.md
          - thinking-functionally/homoiconicity.md
          - thinking-functionally/function-composition.md
          - thinking-functionally/example-hitchhikers-guide.md
          # <!-- TODO - thinking-functionally/iterate-over-values.md -->
          - thinking-functionally/higher-order-functions.md
          - thinking-functionally/immutability.md
          - thinking-functionally/immutable-values.md
          - thinking-functionally/immutable-collections.md
          - thinking-functionally/immutable-local-bindings.md
          - thinking-functionally/partial-functions.md
          - thinking-functionally/map-with-partial.md
          - thinking-functionally/list-comprehension.md
          # <!-- - thinking-functionally/lazy-evaluation.md -->
          - thinking-functionally/sequences.md
          - sequence-abstractions.md
          - thinking-functionally/functors.md
          - thinking-functionally/arity.md
          - thinking-functionally/pattern-matching.md
          - thinking-functionally/polymorphism.md
          - thinking-functionally/recursion.md
          - thinking-functionally/recursion-polymorphism.md
          - thinking-functionally/tail-recursion.md
      - Crreative Coding:
          - reference/creative-coding/index.md
          - SVG:
              - reference/clojure-svg/index.md
      - JVM:
          - reference/jvm/index.md
          - reference/jvm/understanding-memory-usage.md
          - reference/jvm/common-options.md
          - reference/jvm/java-17-flags.md
          - reference/jvm/experimental-options.md
          - Profile tools: reference/jvm/profile-tools.md
          - reference/performance/index.md
      - Alternative Tools:
          - alternative-tools/index.md
          - alternative-tools/clojure-cli/basic-repl.md
          - alternative-tools/clojure-cli/compare-with-leiningen.md
          # - alternative-tools/data-inspector/reveal.md
          - alternative-tools/clojure-cli/evaluate-an-expression.md
          - alternative-tools/clojure-cli/set-namespace-on-repl-startup.md
          - alternative-tools/leiningen/index.md
